services:
  php80:
    build: ./php80
    container_name: php80
    command: php -S 0.0.0.0:8000 -t /var/www/html/moodle/
    ports:
      - "${MOODLE_PORT}:8000"
    environment:
      PHP_IDE_CONFIG: "serverName=${PHPSTORM_SERVER_NAME}"
    restart: always
    volumes:
      - ./moodle:/var/www/html/moodle/
      - ./moodledata:/var/www/html/moodledata/
      - ./php80/configs:/usr/local/etc/php
    extra_hosts:
      - "host.docker.internal:host-gateway"


  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./db-data/mysql:/var/lib/mysql

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - ./db-data/postgres:/var/lib/postgresql/data